### ISSUE TITLE
[Bug] Mutect2: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by jinxin-wang** [jinxin-wang/Genome_Sequencing_Analysis#10]
### GATK version 4.1.4.1 

```
Using GATK jar /mnt/beegfs/software/gatk/4.1.4.1/gatk-package-4.1.4.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx40g -Djava.io.tmpdir=/mnt/beegfs/userdata/j_wang/tmp -jar /mnt/beegfs/software/gatk/4.1.4.1/gatk-package
-4.1.4.1-local.jar Mutect2 --dont-use-soft-clipped-bases true --native-pair-hmm-threads 16 -L /mnt/beegfs/userdata/i_padioleau/genome_data/mm9/interval_mutect2/mm9_20Mb_130.bed --reference /mnt/beegfs/userdata/i_padioleau/genome_data/mm9/bwa_mm9_from_sanger/NCBIM37_um.fa 
--germline-resource /mnt/beegfs/userdata/i_padioleau/genome_data/mm9/genome_project_snp/mgp_V2_snp_indel_mm9.vcf.gz -I bam/x19_mHSC_WT2_CIS_8w_D_3_1_0x.nodup.recal.bam -I bam/x19_mHSC_WT2_CIS_8w_D_1_1_0x.nodup.recal.bam -tumor x19_mHSC_WT2_CIS_8w_D_3_1_0x -normal x19_mHSC
_WT2_CIS_8w_D_1_1_0x -O Mutect2_TvN_tmp/x19_mHSC_WT2_CIS_8w_D_3_1_0x_Vs_x19_mHSC_WT2_CIS_8w_D_1_1_0x_TvN_ON_mm9_20Mb_130.vcf.gz
07:30:53.957 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/beegfs/software/gatk/4.1.4.1/gatk-package-4.1.4.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
May 10, 2023 7:30:54 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
07:30:54.709 INFO  Mutect2 - ------------------------------------------------------------
07:30:54.710 INFO  Mutect2 - The Genome Analysis Toolkit (GATK) v4.1.4.1
07:30:54.710 INFO  Mutect2 - For support and documentation go to https://software.broadinstitute.org/gatk/
07:30:54.710 INFO  Mutect2 - Executing as j_wang@n20 on Linux v3.10.0-957.27.2.el7.x86_64 amd64
07:30:54.710 INFO  Mutect2 - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_152-release-1056-b12
07:30:54.710 INFO  Mutect2 - Start Date/Time: May 10, 2023 7:30:53 AM CEST
07:30:54.710 INFO  Mutect2 - ------------------------------------------------------------
07:30:54.711 INFO  Mutect2 - ------------------------------------------------------------
07:30:54.711 INFO  Mutect2 - HTSJDK Version: 2.21.0
07:30:54.711 INFO  Mutect2 - Picard Version: 2.21.2
07:30:54.711 INFO  Mutect2 - HTSJDK Defaults.COMPRESSION_LEVEL : 2
07:30:54.711 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
07:30:54.712 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
07:30:54.712 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
07:30:54.712 INFO  Mutect2 - Deflater: IntelDeflater
07:30:54.712 INFO  Mutect2 - Inflater: IntelInflater
07:30:54.712 INFO  Mutect2 - GCS max retries/reopens: 20
07:30:54.712 INFO  Mutect2 - Requester pays: disabled
07:30:54.712 INFO  Mutect2 - Initializing engine
07:30:56.308 INFO  FeatureManager - Using codec VCFCodec to read file file:///mnt/beegfs/userdata/i_padioleau/genome_data/mm9/genome_project_snp/mgp_V2_snp_indel_mm9.vcf.gz
07:30:56.621 INFO  FeatureManager - Using codec BEDCodec to read file file:///mnt/beegfs/userdata/i_padioleau/genome_data/mm9/interval_mutect2/mm9_20Mb_130.bed
07:30:56.626 INFO  IntervalArgumentCollection - Processing 20000000 bp from intervals
07:30:56.637 INFO  Mutect2 - Done initializing engine
07:30:56.662 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/mnt/beegfs/software/gatk/4.1.4.1/gatk-package-4.1.4.1-local.jar!/com/intel/gkl/native/libgkl_utils.so
07:30:56.671 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/mnt/beegfs/software/gatk/4.1.4.1/gatk-package-4.1.4.1-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
07:30:56.738 INFO  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
07:30:56.739 INFO  IntelPairHmm - Available threads: 16
07:30:56.739 INFO  IntelPairHmm - Requested threads: 16
07:30:56.739 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
07:30:56.779 INFO  ProgressMeter - Starting traversal
07:30:56.779 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
07:31:05.931 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.0033401610000000003
07:31:05.931 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 0.720194915
07:31:05.931 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 0.26 sec
07:31:05.931 INFO  Mutect2 - Shutting down engine
[May 10, 2023 7:31:05 AM CEST] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.20 minutes.
Runtime.totalMemory()=1911554048
java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.lambda$getGermlineAltAlleleFrequencies$26(SomaticGenotypingEngine.java:339)
        at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.DoublePipeline.toArray(DoublePipeline.java:506)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getGermlineAltAlleleFrequencies(SomaticGenotypingEngine.java:341)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.getNegativeLogPopulationAFAnnotation(SomaticGenotypingEngine.java:324)
        at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.callMutations(SomaticGenotypingEngine.java:146)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:251)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:320)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:308)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:281)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)
```

### Log files 

.snakemake/log/2023-05-09T174605.330922.snakemake.log

logs/Mutect2_TvN/x19_mHSC_WT2_CIS_8w_D_3_1_0x_Vs_x19_mHSC_WT2_CIS_8w_D_1_1_0x_TvN_ON_mm9_20Mb_130.vcf.log

**Comment by jinxin-wang** [comment]
Please refer to https://github.com/broadinstitute/gatk/issues/6695#issuecomment-658207661

**Comment by jinxin-wang** [comment]
Log: 
/mnt/beegfs/scratch/j_wang/99_Pierre/03_Projects/20230316_Mice_WES/.snakemake/log/2023-05-24T172252.981504.snakemake.log

**Comment by jinxin-wang** [comment]
failure results : /mnt/beegfs/scratch/j_wang/99_Pierre/03_Projects/20230316_Mice_WES
success results : /mnt/beegfs/scratch/j_wang/99_Pierre/03_Projects/20230308_Mice_WES

old version for the pipeline(Mice WES): https://github.com/jinxin-wang/DNA_Pipelines/tree/main/DNA/mouse/WES

**Comment by jinxin-wang** [comment]
[Resolved] Caused by the version of java.
